drop table if exists interest;
drop table if exists interest_category;
drop table if exists somoim;
drop table if exists somoim_member;
drop table if exists user_interest;
drop table if exists users;

-- interest: table
CREATE TABLE `interest` (
                            `id` int NOT NULL AUTO_INCREMENT,
                            `name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- interest_category: table
CREATE TABLE `interest_category` (
                                     `seq` int NOT NULL AUTO_INCREMENT,
                                     `interest_id` int DEFAULT NULL,
                                     `name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                     PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- somoim: table
CREATE TABLE `somoim` (
                          `id` int NOT NULL AUTO_INCREMENT,
                          `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `region_code` int DEFAULT NULL,
                          `description` text COLLATE utf8mb4_unicode_ci,
                          `limit` int DEFAULT NULL,
                          `interest_id` int DEFAULT NULL,
                          `creator_id` int DEFAULT NULL,
                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- somoim_member: table
CREATE TABLE `somoim_member` (
                                 `seq` int NOT NULL AUTO_INCREMENT,
                                 `somoim_id` int DEFAULT NULL,
                                 `user_id` int DEFAULT NULL,
                                 `role` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `applied_at` datetime DEFAULT NULL,
                                 `enrolled_at` datetime DEFAULT NULL,
                                 PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- user_interest: table
CREATE TABLE `user_interest` (
                                 `seq` int NOT NULL AUTO_INCREMENT,
                                 `user_id` int DEFAULT NULL,
                                 `interest_id` int DEFAULT NULL,
                                 `interest_category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- users: table
CREATE TABLE `users` (
                         `id` int NOT NULL AUTO_INCREMENT,
                         `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `password` tinytext COLLATE utf8mb4_unicode_ci,
                         `nickname` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `region_code` int DEFAULT NULL,
                         `gender` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `registered_at` datetime DEFAULT NULL,
                         PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

insert into interest (id, name)
values  (1, '아웃도어/여행'),
        (2, '운동/스포츠'),
        (3, '인문학/책/글'),
        (4, '외국/언어'),
        (5, '문화/공연/축제'),
        (6, '음악/악기'),
        (7, '공예/만들기'),
        (8, '댄스/무용'),
        (9, '봉사활동'),
        (10, '사교/인맥'),
        (11, '차/오토바이'),
        (12, '사진/영상'),
        (13, '야구관람'),
        (14, '게임/오락'),
        (15, '요리/제조'),
        (16, '반려동물'),
        (17, '자유주제');

insert into interest_category (seq, interest_id, name)
values  (1, 1, '등산'),
        (2, 1, '산책/트래킹'),
        (3, 1, '캠핑/백패킹'),
        (4, 1, '국내여행'),
        (5, 1, '해외여행'),
        (6, 1, '낚시'),
        (7, 1, '패러글라이딩'),
        (8, 2, '자전거'),
        (9, 2, '배드민턴'),
        (10, 2, '볼링'),
        (11, 2, '테니스/스쿼시'),
        (12, 2, '스키/보드'),
        (13, 2, '골프'),
        (14, 2, '클라이밍'),
        (15, 2, '다이어트'),
        (16, 2, '헬스/크로스핏'),
        (17, 2, '요가/필라테스'),
        (18, 2, '탁구'),
        (19, 2, '당구/포켓볼'),
        (20, 2, '러닝/마라톤'),
        (21, 2, '수영/스쿠버다이빙'),
        (22, 2, '서핑/웨이크보드/요트'),
        (23, 2, '축구/풋살'),
        (24, 2, '농구'),
        (25, 2, '야구'),
        (26, 2, '배구'),
        (27, 2, '승마'),
        (28, 2, '펜싱'),
        (29, 2, '복싱'),
        (30, 2, '태권도/유도'),
        (31, 2, '검도'),
        (32, 2, '무술/주짓수'),
        (33, 2, '스케이트/인라인'),
        (34, 2, '크루즈보드'),
        (35, 2, '족구'),
        (36, 2, '양궁'),
        (37, 3, '책/독서'),
        (38, 3, '인문학'),
        (39, 3, '심리학'),
        (40, 3, '철학'),
        (41, 3, '역사'),
        (42, 3, '시사/경제'),
        (43, 3, '작문/글쓰기'),
        (44, 4, '영어'),
        (45, 4, '일본어'),
        (46, 4, '중국어'),
        (47, 4, '프랑스어'),
        (48, 4, '스페인어'),
        (49, 4, '러시아어'),
        (50, 4, '독일어'),
        (51, 5, '뮤지컬/오페라'),
        (52, 5, '공연/연극'),
        (53, 5, '영화'),
        (54, 5, '전시회'),
        (55, 5, '연기/공연제작'),
        (56, 5, '고궁/문화재탐방'),
        (57, 5, '파티/페스티벌'),
        (58, 6, '노래/보컬'),
        (59, 6, '기타/베이스'),
        (60, 6, '우쿨렐레'),
        (61, 6, '드럼'),
        (62, 6, '피아노'),
        (63, 6, '바이올린'),
        (64, 6, '플룻'),
        (65, 6, '오카리나'),
        (66, 6, '밴드/합주'),
        (67, 6, '작사/작곡'),
        (68, 6, '인디음악'),
        (69, 6, '랩/힙합/DJ'),
        (70, 6, '클래식'),
        (71, 6, '재즈'),
        (72, 6, '락/메탈'),
        (73, 6, '일렉트로닉'),
        (74, 6, '국악/사물놀이'),
        (75, 6, '찬양/CCM'),
        (76, 6, '뉴에이지'),
        (77, 7, '미술/그림'),
        (78, 7, '캘리그라피'),
        (79, 7, '플라워아트'),
        (80, 7, '캔들/디퓨저/석고'),
        (81, 7, '천연비누/화장품'),
        (82, 7, '소품공예'),
        (83, 7, '가죽공예'),
        (84, 7, '가구/목공예'),
        (85, 7, '설탕/앙금공예'),
        (86, 7, '도자/점토공예'),
        (87, 7, '자수/뜨개질'),
        (88, 7, '키덜트/프라모델'),
        (89, 7, '메이크업/네일'),
        (90, 8, '라틴댄스'),
        (91, 8, '사교댄스'),
        (92, 8, '방송/힙합'),
        (93, 8, '스트릿댄스'),
        (94, 8, '발레'),
        (95, 8, '재즈댄스'),
        (96, 8, '한국무용'),
        (97, 8, '밸리댄스'),
        (98, 8, '현대무용'),
        (99, 8, '스윙댄스'),
        (100, 9, '양로원'),
        (101, 9, '보육원'),
        (102, 9, '환경봉사'),
        (103, 9, '사회봉사'),
        (104, 9, '교육/재능나눔'),
        (105, 9, '유기동물보호'),
        (106, 10, '지역'),
        (107, 10, '나이'),
        (108, 10, '파티'),
        (109, 10, '결혼'),
        (110, 10, '와인/커피/차'),
        (111, 10, '맛집/미식회'),
        (112, 11, '현대'),
        (113, 11, '기아'),
        (114, 11, '르노'),
        (115, 11, 'GM'),
        (116, 11, '쌍용'),
        (117, 11, '일본차'),
        (118, 11, '미국차'),
        (119, 11, '유럽차'),
        (120, 11, '바이크'),
        (121, 12, 'DSLR'),
        (122, 12, '필름카메라'),
        (123, 12, '영상제작'),
        (124, 12, '디지털카메라'),
        (125, 13, '삼성라이온즈'),
        (126, 13, '기아타이거즈'),
        (127, 13, '롯데자이언츠'),
        (128, 13, '두산베어스'),
        (129, 13, 'LG트윈스'),
        (130, 13, 'SSG랜더스'),
        (131, 13, '키움히어로즈'),
        (132, 13, '한화이글스'),
        (133, 13, 'NC다이노스'),
        (134, 13, 'KT위즈'),
        (135, 14, '다트'),
        (136, 14, '보드게임'),
        (137, 14, '두뇌심리게임'),
        (138, 14, '온라인게임'),
        (139, 14, '콘솔게임'),
        (140, 14, '단체놀이'),
        (141, 14, '타로카드'),
        (142, 14, '마술'),
        (143, 14, '바둑'),
        (144, 15, '한식'),
        (145, 15, '양식'),
        (146, 15, '중식'),
        (147, 15, '일식'),
        (148, 15, '베이킹/제과'),
        (149, 15, '핸드드립'),
        (150, 15, '소믈리에/와인'),
        (151, 15, '주류제조/칵테일'),
        (152, 16, '강아지'),
        (153, 16, '고양이'),
        (154, 16, '물고기'),
        (155, 16, '파충류'),
        (156, 16, '설치류/중치류'),
        (157, 17, '스피치/발성'),
        (158, 17, '시험/자격증'),
        (159, 17, '취업스터디'),
        (160, 17, '금융보험'),
        (161, 17, '기타 (etc)');